### ISSUE TITLE
Error when run run_unsup_example.sh

### ISSUE THREAD

**Issue by ALiGoo** [princeton-nlp/SimCSE#21] opened 2021-05-03 06:09 UTC
Hi,
I have followed the step in readme to setup my environment. And when I run` evaluation.py` everything is fine. But It will jump out of the error below when I try to run `run_unsup_example.sh` .
```
Traceback (most recent call last):
  File "train.py", line 581, in <module>
    main()
  File "train.py", line 563, in main
    results = trainer.evaluate(eval_senteval_transfer=True)
  File "/home/coh4ry7z/SimCSE/src/trainers.py", line 129, in evaluate
    results = se.eval(tasks)
  File "./SentEval/senteval/engine.py", line 59, in eval
    self.results = {x: self.eval(x) for x in name}
  File "./SentEval/senteval/engine.py", line 59, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "./SentEval/senteval/engine.py", line 127, in eval
    self.results = self.evaluation.run(self.params, self.batcher)
  File "./SentEval/senteval/binary.py", line 49, in run
    enc_input = np.vstack(enc_input)
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/coh4ry7z/.local/share/virtualenvs/SimCSE-IAMR1KOs/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```
Thanks reply!

**Comment by yaoxingcheng** [comment] 2021-05-03 17:31
Hi~ Thank you for pointing this issue. 
We've updated the senteval downstream datasets in huggingface, hopefully the problem is now fixed. 
Run `cd SentEval/data/downstream/ && rm senteval.tar && bash download_dataset.sh` then try to run `run_unsup_example.sh` again to see whether it's good now.

**Comment by ALiGoo** [comment] 2021-05-04 02:35
> Hi~ Thank you for pointing this issue.
> We've updated the senteval downstream datasets in huggingface, hopefully the problem is now fixed.
> Run `cd SentEval/data/downstream/ && rm senteval.tar && bash download_dataset.sh` then try to run `run_unsup_example.sh` again to see whether it's good now.

**Comment by ALiGoo** [comment] 2021-05-04 02:37
Thanks, the problem is solved.

**Closed** 2021-05-04 03:53 UTC
